Clarify Thrust/CUB ABI guarantees
NVIDIA/cccl pull request #1269
Opened 2024-01-10 20:15 UTC by jrhemstad

## Description

Adds `thrust::` to the docs about the archs included as an inline namespace, and further added additional detail about ABI incompatibility between host/device TUs.

2024-01-11 14:32 UTC, robertmaynard requested changes

2024-01-11 14:32 UTC, robertmaynard commented on README.md
> +    - compiled with nvcc vs host compiler only
This should be something like `compiled from a CUDA source file compared to a C++ file`. By a literal reading of this line `nvcc -x c++` would infer same ABI as `nvcc -x cu` which isn't correct. It also fails to distinguish how to reason when `clang++` is both the C++ and CUDA compiler ( no nvcc at all ).

2024-01-11 15:54 UTC, jrhemstad commented on README.md
> +    - compiled with nvcc vs host compiler only
```suggestion
    - compiled as a CUDA source file (`-x cu`) vs C++ source (`-x cpp`)
```

2024-01-11 17:27 UTC, robertmaynard approved these changes

2024-01-13 22:22 UTC, gevtushenko approved these changes

2024-01-16 16:17 UTC, merged