Use relative includes for our public headers
NVIDIA/cccl pull request #1325
Opened 2024-01-26 09:27 UTC by miscco

This ensures we are picking up the right headers and not ones from other include paths.

Also we should ensure that we are properly treated as system headers when we actually have code in the header

2024-01-26 12:37 UTC, miscco commented
@jrhemstad is this something we want to backport to 12.3?

2024-01-26 16:17 UTC, jrhemstad requested changes
What's the context here? I think this is the opposite direction that we want to go in per https://github.com/NVIDIA/cccl/issues/641

2024-01-26 16:21 UTC, miscco commented
> What's the context here? I think this is the opposite direction that we want to go in per #641

We had internal issues with projects, where cccl there was a clash between the cmake provided CCCL and the CTK ones.

Also we are currently doing it everywhere, so we should be consistent until we change the behavior globally.

At least the system_header guards should be mandatory

2024-02-14 14:25 UTC, jrhemstad approved these changes
This is fine for now since tackling https://github.com/NVIDIA/cccl/issues/641 will be a more significant effort and this PR doesn't really make that issue any more complicated to address in the future.

2024-02-14 19:07 UTC, merged