♻️📝 Update `mode` example to use `thrust::unique_count`
NVIDIA/cccl pull request #1354
Opened 2024-02-08 18:52 UTC by codereport

## Description

When this example was created, thrust::unique_count did not exist. It was added in 2022 (2 years ago) in this PR: https://github.com/NVIDIA/thrust/issues/1612. It shouldn't definitely be used now.

I noticed this while @brycelelbach and I were chatting about this algorithm while recording an episode of ADSP 😃

2024-02-08 19:33 UTC, miscco commented
/ok to test

2024-02-08 19:33 UTC, miscco approved these changes

2024-02-08 19:36 UTC, elstehle requested changes
Thanks a lot for updating our examples! 🙏 

Could you please make sure to also include `#include <thrust/unique.h>` and remove `#include <thrust/inner_product.h>`.

2024-02-09 07:46 UTC, elstehle approved these changes

2024-02-09 14:25 UTC, codereport commented
> Thanks a lot for updating our examples! 🙏
> 
> Could you please make sure to also include `#include <thrust/unique.h>` and remove `#include <thrust/inner_product.h>`.

Will do. Can you add me as the assignee so I get a notification? Only saw this because I randomly checked the status of the PR.

2024-02-09 15:38 UTC, miscco commented
/ok to test

2024-02-09 16:46 UTC, merged