Implement `cuda::mr::cuda_pinned_memory_resource`
NVIDIA/cccl pull request #1557
Opened 2024-03-21 10:15 UTC by miscco

Fixes Implement a memory_resource using cudaMallocHost and cudaFreeHost #1516

2024-03-22 18:04 UTC, harrism requested changes
Thanks @miscco ! I have a number of points for discussion and a few suggestions.

2024-03-22 18:04 UTC, harrism commented on libcudacxx/test/libcudacxx/cuda/memory_resource/cuda_pinned_memory_resource/allocate.pass.cpp
> +void ensure_device_ptr(void* ptr) {
Suggestion: rename this since it's not a device pointer.

2024-03-22 18:04 UTC, harrism commented on libcudacxx/test/libcudacxx/cuda/memory_resource/cuda_pinned_memory_resource/allocate.pass.cpp
> +    assert(attributes.type == cudaMemoryTypeHost);
Suggestion: test that the memory is host type *AND* device accessible.

```suggestion
    assert(((attributes.type == cudaMemoryTypeHost) and (attributes.devicePointer != nullptr));
```

2024-03-25 07:14 UTC, miscco commented on libcudacxx/include/cuda/__memory_resource/cuda_pinned_memory_resource.h
> +  void* allocate(const size_t __bytes, const size_t __alignment = __default_cuda_malloc_alignment) const
Actually, for pinned host memory, it would make sense to move towards the host alignment

2024-03-25 07:15 UTC, miscco commented on libcudacxx/include/cuda/__memory_resource/cuda_pinned_memory_resource.h
> +    switch (__status)
I had a commit adding those macros, but thought that it was a bit much. 

Now that I am tinkering with async interfaces, it definitely is the right call

2024-03-25 07:16 UTC, miscco commented on libcudacxx/include/cuda/__memory_resource/cuda_pinned_memory_resource.h
> +   * @throw cuda::cuda_error of the returned error code
I have a PR open to -internally- expose basic exception types Until then this is the best we got

2024-03-25 07:17 UTC, miscco commented on libcudacxx/include/cuda/__memory_resource/cuda_pinned_memory_resource.h
> +  friend constexpr void get_property(cuda_pinned_memory_resource const&, pinned_memory) noexcept {}
That is the issue with those properties.

Both managed and pinned are not as clear cut as the others

2024-03-25 07:19 UTC, miscco commented on libcudacxx/include/cuda/__memory_resource/cuda_pinned_memory_resource.h
> +  constexpr cuda_pinned_memory_resource(const unsigned int __flags = cudaHostAllocDefault) noexcept
My vote would be to keep it simple. I believe few users care that there is pinned device memory, but do care that there is device accessible pinned host memory.

Adding all properties into the name seems a bit of an overkill

2024-03-25 07:21 UTC, miscco commented on libcudacxx/include/cuda/memory_resource
>  #include <cuda/__memory_resource/cuda_managed_memory_resource.h>
That is a very good question.

Generally libcu++ follows the standard library with relative few but heavy headers. I agree that this is not particularly efficient once the list grows, but at the same time we can always make the individual headers public if we feel that it becomes hard to manage.

Just telling a user to `#include <cuda/memory_resource>` is a much simpler solution than listing a bunch of things

2024-03-25 12:24 UTC, miscco commented on libcudacxx/include/cuda/__memory_resource/cuda_pinned_memory_resource.h
> +  void* allocate(const size_t __bytes, const size_t __alignment = __default_cuda_malloc_alignment) const
I have added `__default_cuda_malloc_host_alignment`

2024-03-25 12:29 UTC, miscco commented on libcudacxx/include/cuda/__memory_resource/cuda_pinned_memory_resource.h
> +    const ::cudaError_t __status = ::cudaMallocHost(&__ptr, __bytes, __flags_);
I have the other PR open that exposes `align()` internally. We need that for alignment fiddling

2024-04-02 04:11 UTC, harrism approved these changes
Thanks!

2024-04-02 18:31 UTC, closed without merging

2024-04-03 01:35 UTC, harrism commented on libcudacxx/include/cuda/__memory_resource/cuda_pinned_memory_resource.h
> +    const ::cudaError_t __status = ::cudaMallocHost(&__ptr, __bytes, __flags_);
Can you link me to the other PR?

2024-04-03 01:36 UTC, harrism commented on libcudacxx/include/cuda/__memory_resource/cuda_pinned_memory_resource.h
> +   * @throw cuda::cuda_error of the returned error code
Can you link me the PR?

2024-04-03 07:43 UTC, miscco commented on libcudacxx/include/cuda/__memory_resource/cuda_pinned_memory_resource.h
> +    const ::cudaError_t __status = ::cudaMallocHost(&__ptr, __bytes, __flags_);
I realized it was in the first commit of a followup PR, I opened it [#1583](https://github.com/NVIDIA/cccl/pull/1583)