Disable heterogeneous tests that frequently hang
NVIDIA/cccl pull request #1570
Opened 2024-03-27 07:55 UTC by miscco

Those tests are creating an incredible amount of noise in CI.

We want the functionality tested, but until we can get the tests to unflake, disable them

2024-03-27 17:52 UTC, alliepiper approved these changes
LGTM, open an issue to track fixing and re-enabling these if you haven't already.

2024-03-27 20:38 UTC, wmaxey requested changes
I would only accept this PR if the fix is being actively worked on. I can work on this in the meantime but I don't have an ETA for a fix to the currently UB launch flow.

2024-04-02 14:18 UTC, miscco commented
> I would only accept this PR if the fix is being actively worked on. I can work on this in the meantime but I don't have an ETA for a fix to the currently UB launch flow.

Those tests are continuously breaking some CI run somewhere that get filed as bugs. I do not know of any of those reports that was actually investigated. That means those tests serve no purpose currently

2024-04-05 02:25 UTC, griwes requested changes
We need tests that actually verify the layouts before we merge this.

We can safely drop the abi_v2 versions, as I don't think ABI v2 is still supported, right?

2024-05-08 12:10 UTC, miscco commented
@wmaxey has a PR to fix those tests, so dropping

2024-05-08 12:10 UTC, closed without merging