Cuda_managed_memory_resource
NVIDIA/cccl pull request #1579
Opened 2024-04-02 18:39 UTC by miscco

Fixes Implement a memory_resource using `cudaMallocManaged` and `cudaFree` #1515

Respin of #1556 due to stacked branch issues

2024-04-04 05:53 UTC, harrism requested changes
Looks mostly good to go. A few suggestions.

2024-04-04 05:53 UTC, harrism commented on libcudacxx/include/cuda/__memory_resource/cuda_managed_memory_resource.h
> +   * @brief Allocate device memory of size at least \p __bytes.
Suggestion: It's only device memory the first time it is accessed on the device (or based on cudaMemAdvise hints applied to a range of it). 

```suggestion
   * @brief Allocate CUDA unified memory of size at least \p __bytes.
```

2024-04-04 05:53 UTC, harrism commented on libcudacxx/include/cuda/__memory_resource/cuda_managed_memory_resource.h
> +   * @return void* Pointer to the newly allocated memory
Suggestion: I think doxygen automates documenting the return type, so putting it in the docstring is redundant.

```suggestion
   * @return Pointer to the newly allocated memory
```

2024-04-04 05:53 UTC, harrism commented on libcudacxx/include/cuda/__memory_resource/properties.h
> +struct managed_memory
I think this change requires changes to the documentation. 
https://nvidia.github.io/cccl/libcudacxx/extended_api/memory_resource/properties.html

Specifically: 

> For now, libcu++ provides two commonly used properties: `cuda::mr::device_accessible` and `cuda::mr::host_accessible`.

2024-04-04 05:53 UTC, harrism commented on libcudacxx/test/libcudacxx/cuda/memory_resource/cuda_managed_memory_resource/equality.pass.cpp
> +// Ensure that we can only
Incomplete comment (I saw this in another PR as well -- one that got closed?).

2024-04-04 07:39 UTC, harrism commented on libcudacxx/docs/extended_api/memory_resource/properties.md
> +More properties may be added as the library and the hardware capabilities evolve. However, a user library is free to define as many properties as needed to fully cover its API surface.
Suggestion: simplify, so you don't imply libraries typically need a plethora of properties.

```suggestion
More properties may be added as the library and the hardware capabilities evolve. However, a user library is free to define custom properties.
```

2024-04-04 07:49 UTC, miscco commented on libcudacxx/test/libcudacxx/cuda/memory_resource/cuda_managed_memory_resource/allocate.pass.cpp
> +void ensure_device_ptr(void* ptr) {
I am not sure, in the end we test different functionality and it makes it easier to see what is tested if the function is local

2024-04-04 09:42 UTC, harrism approved these changes

2024-04-05 02:16 UTC, griwes approved these changes

2024-04-12 12:04 UTC, merged