Enable interal use of `std::allocator` related functionality
NVIDIA/cccl pull request #1583
Opened 2024-04-03 07:42 UTC by miscco

This all of the allocator related facilities to be usable internally

2024-04-04 05:54 UTC, harrism commented
This is massive Perhaps the PR description should explain more? Also type in title ("interal").

2024-04-05 02:42 UTC, griwes requested changes
Looks good overall, the cleanup of C++11 checks in the tests is what I'm after the most by requesting changes here.

2024-04-05 02:42 UTC, griwes commented on libcudacxx/include/cuda/std/detail/libcxx/include/__config
> +  || defined(__cuda_std__) // FIXME: Properly handle aligned allocations
The alignment of this line seems wonky.

2024-04-05 02:42 UTC, griwes commented on libcudacxx/include/cuda/std/detail/libcxx/include/__memory/allocation_guard.h
> +  { // not called __release() because it's a keyword in objective-c++
Gotta love objc++.

2024-04-05 02:42 UTC, griwes commented on libcudacxx/include/cuda/std/detail/libcxx/include/__new/allocate.h
> +#if 0 && __has_builtin(__builtin_operator_new) && __has_builtin(__builtin_operator_delete)
What's the actual thing that makes us disable this? I'd rather have that spelled out, even if it's currently universal, than dropping in `false`. Or at least a comment as to why this is disabled would be appreciated.

2024-04-05 02:42 UTC, griwes commented on libcudacxx/include/cuda/std/detail/libcxx/include/__new/allocate.h
> +#if 0 && __has_builtin(__builtin_operator_new) && __has_builtin(__builtin_operator_delete)
Ditto.

2024-04-05 02:42 UTC, griwes commented on libcudacxx/test/libcudacxx/std/utilities/memory/allocator.traits/allocator.traits.members/select_on_container_copy_construction.pass.cpp
> +#if TEST_STD_VER >= 11
Clean all of these up (not only do we no longer support 03, but also these are actually wrong with how our TEST_STD_VER works :'D).

2024-04-05 06:10 UTC, miscco commented on libcudacxx/include/cuda/std/detail/libcxx/include/__config
I used the formatter to give it a better look.

god I hate what that does to macros

2024-04-11 08:31 UTC, miscco commented
@griwes can you give this another look?

2024-04-13 17:12 UTC, griwes approved these changes

2024-04-13 17:12 UTC, merged