Project Automation: Move PR and Linked Issues to In Progress
NVIDIA/cccl pull request #170
Opened 2023-07-06 14:24 UTC by jarmak-nv

## Description

closes #169 

This PR creates a new GitHub action, `project_automation_set_in_progress.yml`. It uses the ProjectsV2 graphQL API to perform the automations. This was designed to not require any external tools, nor install anything into the Actions runner to minimize runtime. 

### Steps
- Set up some hard-coded environment variables
   - These are public, static, and in doing so we simplify and accelerate the GHA
   - Should they ever become dynamic, they can be replaced with queries
- Find out what the PR's Project-Specific ID is
   - The ProjectsV2 API creates a specific ID for each item within a project. It is not directly accessible through the PR unfortunately
- Find out the PR's current status
   - This action runs any time a PR is [opened, or edited
](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)
   - Because of the `edited` trigger (which we need if we want to add additional issue links after opening the PR) it's possible the action could trigger when the PR is in the `Review` status, or `Done`
- If the PR status is `Todo` or `null`, update the PR to `In Progress`
- If the PR status is `Todo` or `null`, update the linked issues to `In Progress`

All steps have `continue-on-error: True` so that this action cannot count as a failure when considering it as a CI check. It will make failures silent and we'll need to manually watch for failure, but I think it's an acceptable tradeoff.

## Checklist
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-07-06 15:44 UTC, jrhemstad commented on .github/workflows/project_automation_set_in_progress.yml
> +                           .node.id' project_data.json)
I'm surprised by how complicated the graphql API makes this operation. We need to query all the projects a PR could belong to and then filter to the specific `PROJECT_ID`? 

I would think it'd be simpler to get the id of the PR for a given project...

2023-07-06 17:21 UTC, jarmak-nv commented on .github/workflows/project_automation_set_in_progress.yml
> + GH_TOKEN: ${{ secrets.PROJECT_MANAGEMENT_SECRET }}  # !!TODO: REPLACE WITH A TOKEN THAT HAS PROJECT MANAGEMENT PERMISSIONS!!
Done!

2023-07-07 14:03 UTC, jarmak-nv commented
After some talks + seeing some potential, I'm reworking this to be a little more "full automation".

2023-07-07 15:47 UTC, jarmak-nv commented
Testing [graphQL mutation](https://docs.github.com/en/graphql/reference/mutations#convertpullrequesttodraft) for setting to draft.

2023-07-10 18:20 UTC, jrhemstad commented on .github/workflows/project_automation_set_in_progress.yml
Do we just want to add a `project_automation/` directory instead of prefixing the workflow file names?

2023-07-10 19:09 UTC, jrhemstad approved these changes
I obviously didn't go through all the graphql stuff in detail, but I followed the high level workflow and it looks awesome!

Do we want to update any of the process docs in the Wiki as part of this PR? I really like the idea of having a state diagram in there so it's easy to see at a glance how a PR/issue evolves over time.

2023-07-10 19:34 UTC, jarmak-nv commented on .github/workflows/project_automation_set_in_progress.yml
tbh I didn't know that was an option, I thought all workflows had to be in the `.workflows/` folder. Happy to move them and remove the prefix!

2023-07-11 16:40 UTC, jarmak-nv reviewed
Test "review"

2023-07-11 16:46 UTC, jarmak-nv reviewed
~App Test 2~ The functional skip logic made it not generate a token. But it shows as a failure.

2023-07-11 16:53 UTC, jrhemstad requested changes
test requesting changes

2023-07-27 19:41 UTC, jrhemstad approved these changes

2023-07-27 19:44 UTC, jrhemstad commented
Merging this with the failed check. This failure is expected because the action needs access to repo secrets that aren't available on forks. It has been tested elsewhere and confirmed that it will work once merged.

2023-07-27 19:44 UTC, merged