Add guard against half support
NVIDIA/cccl pull request #1735
Opened 2024-05-13 17:58 UTC by miscco

This mirrors our current escape hatch against `__nv_bfloat16` to also allow the user to disable half support

Addresses: #1727

2024-05-15 03:17 UTC, gevtushenko requested changes
Left a few comments. Please, let me know when CTK 12.1 can build our tests and I'll have another look.

2024-05-15 03:17 UTC, gevtushenko commented on cub/cub/device/dispatch/dispatch_histogram.cuh
> +        scale.fraction.range));
critical: this yields different result in presence of integer promotion. I don't think we can make this change:
```cpp
  char sample = 100;
  char min_level = 0;
  char max_level = 120;
  CommonT bins = 120;
  CommonT range = max_level - min_level;
  std::cout << OldComputeBin(sample, min_level, bins, range) << std::endl; // 100
  std::cout << NewComputeBin(sample, min_level, bins, range) << std::endl; // 0
```

2024-05-15 03:17 UTC, gevtushenko commented on cub/cub/util_type.cuh
> +#endif // !CUB_DISABLE_BF16_SUPPORT && CUB_DISABLE_FP16_SUPPORT
suggestion: it's not exactly trivial that bf16 includes fp16, and if fp16 is disabled we also have to disable bf16. Could you please add a comment? Also, we might want to document this for users:
```cpp
#ifdef DOXYGEN_SHOULD_SKIP_THIS

/**
 * @def CCCL_DISABLE_FP16_SUPPORT
 *
 * Has to disable BF16 support as well, etc.
 */
#  define CCCL_DISABLE_FP16_SUPPORT

#endif
```

2024-05-15 07:18 UTC, miscco commented on cub/cmake/CubHeaderTesting.cmake
> +cub_add_header_test(half "${header_definitions}")
I changed it so that we are more explicit

2024-05-15 11:56 UTC, miscco commented
@gevtushenko I have reworked the approach and ditched the `cuda::std::meow` functors.

It now directly utilizes the builtin functions when possible and falls back to float when needed.

I also went ahead and started a centralization of the detection so that we do not duplicate all that logic

2024-05-15 20:53 UTC, gevtushenko requested changes
Thank you for addressing the issues! There are a few more breaking changes. Please, let me know when those are addressed and I'll have another look.

2024-05-15 20:53 UTC, gevtushenko commented on cub/cub/util_type.cuh
> -#    include <cuda_fp8.h>
critical: the removed code used to include fp8 header. Code below relies on `__CUDA_FP8_TYPES_EXIST__`. The change removed fp8 include along with the fp8 types support. This now doesn't compile:

```cpp
#include <cub/block/block_radix_sort.cuh>
#include <cuda_fp8.h>

__global__ void kernel() {
    __nv_fp8_e4m3 data[3];

    using block_sort_t = cub::BlockRadixSort<__nv_fp8_e4m3, 256, 3>;
    using temp_storage_t = block_sort_t::TempStorage;

    __shared__ temp_storage_t temp_storage;
    block_sort_t(temp_storage).Sort(data);
}
```

2024-05-23 06:04 UTC, gevtushenko commented on cub/cmake/CubHeaderTesting.cmake
> +  "CCCL_DISABLE_BF16_SUPPORT")
I think we should keep testing with `CUB_DISABLE_BF16_SUPPORT` to make sure we do not break it

2024-05-23 06:04 UTC, gevtushenko approved these changes

2024-05-27 08:51 UTC, merged