Fix issues with comments in the concept emulation
NVIDIA/cccl pull request #1931
Opened 2024-07-02 14:29 UTC by miscco

Those comments were ment to force clang-format into doing not so bad things with the concept emulation.

However, with the recent versions of clang-format this is not necessary anymore

2024-07-02 14:33 UTC, bernhardmgruber approved these changes

2024-07-02 14:35 UTC, bernhardmgruber requested changes

2024-07-02 14:43 UTC, miscco commented on libcudacxx/include/cuda/std/detail/libcxx/include/span
> +             (integral_constant<bool, static_cast<decltype(_Tp::value)>(_Tp()) == _Tp::value>::value) //
I verified that we can build all public headers with gcc -C option locally now

2024-07-02 14:49 UTC, bernhardmgruber approved these changes

2024-07-02 14:49 UTC, bernhardmgruber commented on libcudacxx/include/cuda/std/__ranges/subrange.h
> +// We relaxthe requirement on tuple_size due to a gcc issue
```suggestion
// We relax the requirement on tuple_size due to a gcc issue
```

2024-07-02 14:57 UTC, bernhardmgruber approved these changes

2024-07-03 09:17 UTC, bernhardmgruber approved these changes

2024-07-03 11:17 UTC, merged