Move towards libfmt, to allow different host compilers
NVIDIA/cccl pull request #2336
Opened 2024-08-30 07:19 UTC by miscco

This makes it easier to integrate into other infrastructures

See #2334

2024-08-30 08:35 UTC, miscco commented
This successfully detects changes to the c library:
```
### Modifications in project?

|     | Project
|-----|---------
| +/- | CCCL Infrastructure
|     | libcu++
|     | CUB
|     | Thrust
|     | CUDA Experimental
|     | pycuda
| +/- | CUDA C Core Library 
```

2024-08-30 10:19 UTC, bernhardmgruber approved these changes

2024-08-30 13:19 UTC, leofang reviewed
Thanks, Michael! Left a comment based on my understanding of the component relation.

2024-08-30 13:19 UTC, leofang commented on ci/inspect_changes.sh
>    [pycuda]="cccl libcudacxx cub thrust cudax"
`cuda.parallel` depends on the C library:
```suggestion
  [pycuda]="cccl libcudacxx cub thrust c"
```

2024-08-30 18:22 UTC, gevtushenko requested changes
CCCL/c is producing a binary, not sources, so there's no immediate need for a wide compiler matrix support. Regarding the fmt dependency, we fetch it as part of libcu++ codegen project once and fetch it in different way as part of nvbench setup in our benchmarks. I don't know if this can create conflicts for development preset. Let's focus this PR on CI dependencies and figure out CCCL-wide fmt availablility after https://github.com/NVIDIA/cccl/pull/2338 is merged.

2024-08-30 20:28 UTC, alliepiper approved these changes
Signing off on the `inspect_changes.sh` update.

2024-09-02 17:11 UTC, gevtushenko approved these changes

2024-09-02 17:14 UTC, merged