nvrtc wants `integral_constant`'s functions host/device annotated
NVIDIA/cccl pull request #2401
Opened 2024-09-10 20:27 UTC by ericniebler

## Description

in the CI runs of my `__type_list` pr, i'm seeing nvrtc failures such as:

```
  5: /home/coder/cccl/libcudacxx/include/cuda/std/__type_traits/integral_constant.h(31): 
error: A function without execution space annotations (__host__/__device__/__global__) is 
considered a host function, and host functions are not allowed in JIT mode. Consider using -
default-device flag to process unannotated functions as __device__ functions in JIT mode
  5:     _LIBCUDACXX_HIDE_FROM_ABI constexpr operator value_type() const noexcept
  5:                                         ^
  5:           detected during:
  5:             instantiation of class "cuda::std::__4::integral_constant<_Tp, __v> [with
_Tp=<error-type>, __v=<error-constant>]" at line 359 of
/home/coder/cccl/libcudacxx/include/cuda/std/__type_traits/type_list.h
```

this pr adds the missing host/device annotations. as a drive-by, it guards the redefinition of the `::value` class static with the appropriate feature test.

## Checklist

- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2024-09-10 20:42 UTC, bernhardmgruber approved these changes

2024-09-10 20:58 UTC, miscco requested changes
That should not be necessary, the `_LIBCUDACXX_HIDE_FROM_ABI` already contains that

2024-09-10 21:36 UTC, ericniebler commented
then something is going on with the nvrtc build that i don't understand

2024-09-11 06:36 UTC, miscco commented
My guess is that we recently moved that from `_LIBCUDACXX_INLINE_VISIBILITY` to `_LIBCUDACXX_HIDE_FROM_ABI` and someone includes an old header first that does not know this new definition

2024-09-11 17:09 UTC, closed without merging