Replace `thrust::complex` with `std::complex`
NVIDIA/cccl pull request #260
Opened 2023-07-24 13:48 UTC by miscco

There are some notable differences though. thrust::complex has been a
bit more lenient when determining the type of arithmetic operations.

That said, I believe being more strict is actually a feature not a bug

2023-07-25 14:25 UTC, senior-zero requested changes
I've left a few comments on places that break API. I haven't covered all the changes, but I think that the comments should be applicable to the rest of them.

2023-07-25 14:25 UTC, senior-zero commented on thrust/thrust/detail/complex/arithmetic.h
> -}
The following code used to work, but now it doesn't:
```cpp
  thrust::complex<float> a;
  thrust::complex<double> b;
  auto c = a + b;
```
I think we need to keep this overload and maybe mark it as deprecated. Same with other operators.

2023-07-25 14:25 UTC, senior-zero commented on thrust/thrust/detail/complex/arithmetic.h
> -}
The following code used to work, but now it doesn't:

```cpp
  float a = 84;
  thrust::complex<double> b(42, 42);
  auto c = a + b;
```
I think we need to keep this overload and maybe mark it as deprecated. Same with other operators.

2023-07-25 14:25 UTC, senior-zero commented on thrust/thrust/detail/complex/arithmetic.h
> -T abs(const complex<T>& z)
The following code used to work, now it doesn't:
```cpp
  thrust::complex<double> a;
  auto b = thrust::abs(a);
```

2023-07-25 14:25 UTC, senior-zero commented on thrust/thrust/detail/complex/arithmetic.h
> -T arg(const complex<T>& z)
The following code used to work, now it doesn't:
```cpp
  thrust::complex<double> a;
  auto b = thrust::arg(a);
```

2023-09-22 08:49 UTC, miscco commented
Dropping in favor of #454

2023-09-22 08:49 UTC, closed without merging