`std::dims`
NVIDIA/cccl pull request #2961
Opened 2024-11-25 22:10 UTC by fbusato

Address https://github.com/NVIDIA/cccl/issues/2810

## Description

Add C++26 `std::dims` alias template backport to C++17 (aligned with `mdspan`)  https://en.cppreference.com/w/cpp/container/mdspan/extents

2024-11-25 22:23 UTC, pciolkosz approved these changes
I know this is a simple alias, but should there be at least one small test case that will use it for something trivial, just to make sure it's available, not under wrong ifdef etc?

2024-11-25 23:14 UTC, fbusato commented
good point. I will do that

2024-11-26 08:02 UTC, miscco requested changes

2024-11-26 08:02 UTC, miscco commented on libcudacxx/test/libcudacxx/std/containers/views/mdspan/mdspan.extents.dims/compare.pass.cpp
> +// SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES.
```suggestion
// SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES.
```

2024-11-26 08:02 UTC, miscco commented on libcudacxx/test/libcudacxx/std/containers/views/mdspan/mdspan.extents.dims/compare.pass.cpp
> +    assert(e0 == e1);
Yeah we should do that
```suggestion
    cuda::std::dextents<index_t, 3> e0{1, 2, 3};
    cuda::std::dims<3> e1{1, 2, 3};

    static_assert(cuda::std::is_same<decltype(e0), decltype(e1)>::value, "");
    assert(e0 == e1);
```

2024-11-26 08:03 UTC, miscco approved these changes

2024-11-26 08:03 UTC, bernhardmgruber approved these changes

2024-11-26 09:32 UTC, merged