Drop _CCCL_ELSE_IF_CONSTEXPR
NVIDIA/cccl pull request #2966
Opened 2024-11-26 09:59 UTC by bernhardmgruber

It's no longer needed.

2024-11-26 10:02 UTC, miscco requested changes
I believe we are getting some use cases of that with the safe integer functions and this is genuinely useful

2024-11-26 10:15 UTC, bernhardmgruber commented
> I believe we are getting some use cases of that with the safe integer functions and this is genuinely useful

Why do I need `_CCCL_ELSE_IF_CONSTEXPR` if I can just write `else _CCCL_IF_CONSTEXPR`?

2024-11-26 14:24 UTC, davebayer commented
> I believe we are getting some use cases of that with the safe integer functions and this is genuinely useful

I've removed it from the branch.

2024-11-30 15:41 UTC, miscco approved these changes

2024-11-30 18:39 UTC, merged