GH Infra: project automation and issue template fixes
NVIDIA/cccl pull request #297
Opened 2023-08-03 14:53 UTC by jarmak-nv

## Description

closes #296 
closes #263 

This PR changes the project automation workflows from using the GitHub app authentication to an org secret - this _should_ resolve the failures during the `pull_request_review` action trigger.

It also fixes the issue template labels so they should be correctly pre-assigned.

## Checklist
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-08-03 15:08 UTC, jrhemstad requested changes
test

2023-08-03 17:07 UTC, senior-zero approved these changes

2023-08-10 19:29 UTC, jarmak-nv commented
After a bunch of digging and testing here's the results:
- We technically could make this workflow work by creating a secondary workflow that's triggered by the `pull_request_review` which then runs in the context of the repo, but it's not an implementation I'm happy with and it drives up action-minute consumption
- Instead I've changed it so on `pull_request_review` it sets to draft then exits successfully
- Inside the project, I've enabled the built-in workflow to change the status to `In Progress` so the PR will automatically have its status change

This largely achieves the same results, except linked issues do not follow the status. We could edit https://github.com/NVIDIA/cccl/blob/main/.github/workflows/project_automation_sync_pr_issues.yml to be on `synchronize` as well, but I worry that would cause excessive unnecessary runs (it would run on every commit). Open to thoughts here.

Unfortunately, the default github token cannot trigger actions, otherwise the conversion to draft would re-trigger this action and make the challenges moot.

2023-08-16 15:07 UTC, jrhemstad approved these changes

2023-08-16 16:25 UTC, merged