Hide third party cmake options in our cmake developer builds.
NVIDIA/cccl pull request #300
Opened 2023-08-03 18:56 UTC by allisonvacanti

This patch adds a place to list cmake options from our dependencies (e.g. Catch2, etc) that we don't want to display when configuring a developer build with tools like `ccmake` and `cmake-gui`.

Fixes #299.

## Description

closes #299

Simplifies the process of interactively configuring a CCCL build using tools like `ccmake` and `cmake-gui`.

2023-08-03 19:19 UTC, robertmaynard requested changes

2023-08-03 19:19 UTC, robertmaynard commented on CMakeLists.txt
> +include(cmake/CCCLHideThirdPartyOptions.cmake)
This needs to be done at the end of the CMakeLists.txt

Variables passed to mark_as_advanced that are not already in the cache are ignored ( policy 102 ).

So we want to do this at the end so these are hidden after first CMake execution.

2023-08-31 23:21 UTC, allisonvacanti commented
@robertmaynard This is ready for another look.

2023-09-01 13:50 UTC, robertmaynard approved these changes

2023-09-02 12:20 UTC, merged