use clang-format in dev containers
NVIDIA/cccl pull request #513
Opened 2023-10-01 12:41 UTC by miscco

Currently we did not install clang-format in our dev containers

This lead to bad user experience, so with the latest iteration of the dev containers we get clang-format-17

We use that fixed version to avoid any differences between the different clang-format versions

Also add a clang-format file for libcu++ and apply it throughout the codebase

2023-10-01 14:45 UTC, senior-zero requested changes
I'm going to come up with a single clang-format file for CCCL. Could you please limit your changes to devcontainer updates for now? Side note, formatting PRs need .git-blame-ignore-revs.

2023-10-01 17:10 UTC, miscco commented
> Side note, formatting PRs need .git-blame-ignore-revs.

The issue is that the the `.git-blame-ignore-revs` file takes the hash of the commit. Given that we want to merge this as a "rebase and merge" to be able to cleanly revert it in case of issues we do not know the hash beforehand, because that is contingent on the rebase during the "merge". So I opted to not include the file to the repo

> I'm going to come up with a single clang-format file for CCCL. Could you please limit your changes to devcontainer updates for now? 

I am not sure if we really want a *single* clang-format file for the whole repo instead of one per library. That said I am open for a unified one, but due to libcu++ being a bit special, we will require a lot of the clang-format file I added here. 

Feel free to propose changes to the format file, I am quite positive that we will find a common one

2023-10-09 17:56 UTC, jrhemstad commented
fyi, this is a handy tool for experimenting with formatting: https://clang-format-configurator.site/

Basically godbolt for clang format.

2023-10-11 20:15 UTC, senior-zero commented
@miscco I've based https://github.com/NVIDIA/cccl/issues/544 on assumption that devcontainer changes from this PR are merged first. Could you please remove auto formatting and merge devcontainer changes first?

2023-10-18 17:08 UTC, senior-zero approved these changes

2023-10-19 10:45 UTC, merged